os: linux
dist: focal
language: node_js
node_js:
  - 12.13.0
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  strategy: git
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  on:
    branch: gh-pages
