os: linux
dist: focal
language: node_js
node_js:
  - 12.13.0
cache: npm

install:
  - npm ci

script:
  - npm run test
  - npm run e2e
  - npm run build

deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
